import requests
res = requests.get(f"http://localhost:5000/api/students/3/1/")
print(res.status_code)
print(res.json().get('info'))
print(res.json())
k=res.json().get('info')
print("")
print(k)
print("")
print(k.get('student'))
print("")
print(k.get('marks'))
for mark in k.get('marks'):
    print("")
    print(mark.get('subject'))
    print(mark.get('marks'))
    print(mark.get('grade'))
# res = requests.get("http://localhost:5000/api/students/1")
# print(res.status_code)
# print(res.json().get('message'))